# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8319a204ce13f858fe016b2781535e25c24fda8a5456887d3fb5fc1117725bbd5e53d214c363132d2d28a88181562face7853cafeb6f4339b7242d4d1178fc1c

test:
  secret_key_base: 99b8bff9327936afd7adbc5d75f39949e812fe92841a02bb839d5d59f13372bef97a06371f256f90c104414fea6c6d9bd9fef130e97466b243ef74a555210e6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
